In [1]:
import numpy as np

sample_list = [1, 2, 3]

np.array(sample_list)

array([1, 2, 3])

In [2]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.arange(0,5)

#Returns array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [4]:
np.arange(1,11,2)

#Returns array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [5]:
np.zeros(4)

#Returns array([0, 0, 0, 0])

array([0., 0., 0., 0.])

In [6]:
np.ones(5)

#Returns array([1, 1, 1, 1, 1])

array([1., 1., 1., 1., 1.])

In [7]:
np.linspace(0, 1, 10)

#Returns array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.eye(1)

#Returns a 1x1 identity matrix

array([[1.]])

In [9]:
np.eye(2)

#Returns a 2x2 identity matrix

array([[1., 0.],
       [0., 1.]])

In [10]:
np.eye(50)

#Returns a 50x50 identity matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [11]:
np.random.rand(5,5)

#Returns a sample of random numbers between 0 and 1.
#Sample size can either be one integer (for a one-dimensional array) or two integers separated by commas (for a two-dimensional array).

array([[0.53524562, 0.43781408, 0.43446447, 0.72424577, 0.27001344],
       [0.33454852, 0.19644288, 0.41708748, 0.38275278, 0.44784076],
       [0.16910067, 0.67203025, 0.58469225, 0.17767874, 0.02716207],
       [0.74191383, 0.00300642, 0.78362722, 0.76855133, 0.6474682 ],
       [0.13917984, 0.54331917, 0.99233967, 0.72223236, 0.49584134]])

In [12]:
np.random.randn(3,3)

#Returns a sample of random numbers between 0 and 1, following the normal distribution.

#Sample size can either be one integer (for a one-dimensional array) or two integers separated by commas (for a two-dimensional array).

array([[-0.4210539 , -0.39522632, -0.02049809],
       [ 1.82521835,  0.48874378,  0.58843735],
       [ 2.15965434, -2.09753772, -0.1733431 ]])

In [13]:
np.random.randint(1, 10, 3)

#Returns a sample of integers that are greater than or equal to 'low' and less than 'high'

array([2, 7, 3])

In [14]:
arr = np.array([0,1,2,3,4,5])

arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
import numpy as np
arr = np.array([0,1,2,3,4,5])

arr.shape

#Returns (6,) - note that there is no second element since it is a one-dimensional array

(6,)

In [16]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
arr = arr.reshape(2,3)

arr.shape

#Returns (2,3)

(2, 3)

In [20]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
arr.reshape(2,3).shape

#Returns (2,3)

(2, 3)

In [17]:
arr = np.array([1, 2, 3, 4])
arr.max()

#Returns 4

np.int64(4)

In [18]:
arr = np.array([1, 2, 3, 4])
arr.argmax()

#Returns 3

np.int64(3)

In [22]:
import numpy as np
simple_array = np.array([1, 2, 3, 4])
simple_array.min()

#Returns 1

np.int64(1)

In [21]:
import numpy as np
simple_array = np.array([1, 2, 3, 4])
simple_array.argmin()

#Returns 0

np.int64(0)

In [23]:
arr = np.arange(4)

arr

array([0, 1, 2, 3])

In [25]:
arr = np.arange(4)
2 + arr

#Returns array([2, 3, 4, 5])

array([2, 3, 4, 5])

In [26]:
arr = np.arange(4)
arr + arr

#Returns array([0, 2, 4, 6])

array([0, 2, 4, 6])

In [27]:
arr = np.arange(4)
arr - 10

#Returns array([-10,  -9,  -8,  -7])

array([-10,  -9,  -8,  -7])

In [28]:
arr = np.arange(4)
arr - arr

#Returns array([0, 0, 0, 0])

array([0, 0, 0, 0])

In [29]:
arr = np.arange(4)
6 * arr

#Returns array([ 0,  6, 12, 18])

array([ 0,  6, 12, 18])

In [30]:
arr = np.arange(4)
arr * arr

#Returns array([0, 1, 4, 9])

array([0, 1, 4, 9])

In [31]:
arr = np.arange(4)
arr / 2

#Returns array([0. , 0.5, 1. , 1.5])

array([0. , 0.5, 1. , 1.5])

In [32]:
arr = np.arange(4)
arr / arr

#Returns array([nan,  1.,  1.,  1.])

<ipython-input-32-3113746945>:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.])

In [33]:
arr = np.arange(4)
np.sqrt(arr)

#Returns array([0., 1., 1.41421356, 1.73205081])

array([0.        , 1.        , 1.41421356, 1.73205081])

In [34]:
arr = np.arange(4)
np.exp(arr)

#Returns e^element for every element in the array

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [35]:
arr = np.arange(4)
np.sin(arr)

#Calculate the trigonometric sine of every value in the array

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [36]:
arr = np.arange(4)
np.cos(arr)

#Calculate the trigonometric cosine of every value in the array

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [37]:
arr = np.arange(4)
np.log(arr)

#Calculate the base-ten logarithm of every value in the array

<ipython-input-37-1922355535>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [39]:
arr = np.random.rand(5)
arr

array([0.15368823, 0.92674627, 0.41050626, 0.97483917, 0.74898692])

In [40]:
arr = np.round(arr, 2)
arr

array([0.15, 0.93, 0.41, 0.97, 0.75])

In [41]:
arr[0]

#Returns 0.69

np.float64(0.15)

In [42]:
arr[:]

#Returns the entire array: array([0.69, 0.94, 0.66, 0.73, 0.83])

array([0.15, 0.93, 0.41, 0.97, 0.75])

In [43]:
arr[1:]

#Returns array([0.94, 0.66, 0.73, 0.83])

array([0.93, 0.41, 0.97, 0.75])

In [44]:
arr[1:4]

#Returns array([0.94, 0.66, 0.73])

array([0.93, 0.41, 0.97])

In [47]:
arr[:] = [0.12, 0.94, 0.66, 0.73, 0.83]
arr

#Returns array([0.12, 0.94, 0.66, 0.73, 0.83])

array([0.12, 0.94, 0.66, 0.73, 0.83])

In [48]:
arr[:] = 0

arr

#Returns array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [49]:
arr[2:5] = 0.5

arr

#Returns array([0. , 0. , 0.5, 0.5, 0.5])

array([0. , 0. , 0.5, 0.5, 0.5])

In [50]:
new_array = np.array([6, 7, 8, 9])

second_new_array = new_array[0:2]

second_new_array

#Returns array([6, 7])

array([6, 7])

In [51]:
second_new_array[1] = 4

second_new_array

#Returns array([6, 4]), as expected


array([6, 4])

In [54]:
new_array

#Returns array([6, 4, 8, 9])

array([6, 4, 8, 9])

In [57]:
array_to_copy = np.array([1, 2, 3])

copied_array = array_to_copy.copy()

array_to_copy

#Returns array([1, 2, 3])

array([1, 2, 3])

In [56]:
copied_array

#Returns array([1, 2, 3])

array([1, 2, 3])

In [58]:
copied_array[0] = 9

copied_array

#Returns array([9, 2, 3])

array([9, 2, 3])

In [59]:
array_to_copy

#Returns array([1, 2, 3])

array([1, 2, 3])

In [61]:
mat = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])

mat

#Returns:

#array([[ 5, 10, 15],
#      [20, 25, 30],
#      [35, 40, 45]])

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
#First, let's get the first row:

mat[0]

array([ 5, 10, 15])

In [63]:
#Next, let's get the last element of the first row:

mat[0][-1]

np.int64(15)

In [64]:
mat[1:][:2]

#Returns:

#array([[20, 25, 30],
#      [35, 40, 45]])

array([[20, 25, 30],
       [35, 40, 45]])

In [65]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])

arr > 0.7

#Returns array([False,  True, False,  True,  True])

array([False,  True, False,  True,  True])

In [66]:
arr[arr > 0.7]

#Returns array([0.94, 0.73, 0.83])

array([0.94, 0.73, 0.83])